"""PDF report generation tools.

Provides functionality to generate styled PDF reports from data.
"""

import os
from datetime import datetime

from langchain.tools import tool
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from agent.async_utils import run_in_thread
from agent.custom_tools.report_io import prepare_report_output_path


def _generate_pdf_report_sync(
    title: str,
    content: str,
    output_path: str = "./reports/report.pdf",
    subtitle: str | None = None,
) -> str:
    """Generate a styled PDF report.

    Args:
        title: The title of the report
        content: The main content of the report
        output_path: The path where the PDF will be saved (default: ./reports/report.pdf)
        subtitle: Optional subtitle for the report

    Returns:
        A message indicating success or failure with the file path
    """
    try:
        prepare_report_output_path(output_path)

        # Create PDF document
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
        )

        # Get sample styles
        styles = getSampleStyleSheet()

        # Create custom styles
        title_style = ParagraphStyle(
            "CustomTitle",
            parent=styles["Heading1"],
            fontSize=24,
            textColor=colors.HexColor("#2c3e50"),
            spaceAfter=30,
            alignment=1,  # Center
        )

        subtitle_style = ParagraphStyle(
            "CustomSubtitle",
            parent=styles["Heading2"],
            fontSize=14,
            textColor=colors.HexColor("#34495e"),
            spaceAfter=20,
            alignment=1,  # Center
        )

        body_style = ParagraphStyle(
            "CustomBody",
            parent=styles["BodyText"],
            fontSize=11,
            leading=14,
            textColor=colors.HexColor("#2c3e50"),
            spaceAfter=12,
        )

        # Build content
        story = []

        # Add title
        story.append(Paragraph(title, title_style))

        # Add subtitle if provided
        if subtitle:
            story.append(Paragraph(subtitle, subtitle_style))

        # Add date
        date_style = ParagraphStyle(
            "DateStyle",
            parent=styles["Normal"],
            fontSize=10,
            textColor=colors.HexColor("#7f8c8d"),
            alignment=1,
        )
        story.append(
            Paragraph(
                f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
                date_style,
            )
        )
        story.append(Spacer(1, 0.3 * inch))

        # Add horizontal line
        line_table = Table(
            [[""]],
            colWidths=[7.5 * inch],
        )
        line_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#ecf0f1")),
                    ("LINEBELOW", (0, 0), (-1, -1), 2, colors.HexColor("#3498db")),
                    ("ROWHEIGHTS", (0, 0), (-1, -1), 0.05 * inch),
                ]
            )
        )
        story.append(line_table)
        story.append(Spacer(1, 0.2 * inch))

        # Add main content (split by lines)
        content_lines = content.split("\n")
        for line in content_lines:
            if line.strip():
                story.append(Paragraph(line.strip(), body_style))
            else:
                story.append(Spacer(1, 0.1 * inch))

        # Add footer
        story.append(Spacer(1, 0.3 * inch))
        footer_style = ParagraphStyle(
            "FooterStyle",
            parent=styles["Normal"],
            fontSize=9,
            textColor=colors.HexColor("#95a5a6"),
            alignment=1,
        )
        story.append(
            Paragraph("Generated by YouTube Community Manager Agent", footer_style)
        )

        # Build PDF
        doc.build(story)

        file_size = os.path.getsize(output_path)
        return f"PDF report successfully generated: {output_path} ({file_size} bytes)"

    except Exception as e:
        return f"Error generating PDF report: {str(e)}"


MEDICAL_THEME = {
    "title": "#1a5276",
    "subtitle": "#117a65",
    "section_header_bg": "#1a5276",
    "section_header_text": "#ffffff",
    "body": "#2c3e50",
    "accent_line": "#27ae60",
    "footer": "#95a5a6",
    "intro_bg": "#eafaf1",
    "causes_bg": "#fdedec",
    "prevention_bg": "#eafaf1",
    "treatment_bg": "#ebf5fb",
}


def _generate_stylized_topic_pdf_sync(
    topic: str,
    sections: dict[str, str],
    output_path: str,
    subtitle: str = "",
    intro_text: str = "",
) -> str:
    """Generate a color-themed PDF report with structured sections."""
    try:
        prepare_report_output_path(output_path)

        theme = MEDICAL_THEME
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=0.65 * inch,
            leftMargin=0.65 * inch,
            topMargin=0.65 * inch,
            bottomMargin=0.65 * inch,
        )
        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "TopicTitle",
            parent=styles["Heading1"],
            fontSize=26,
            textColor=colors.HexColor(theme["title"]),
            spaceAfter=8,
            alignment=1,
            fontName="Helvetica-Bold",
        )
        subtitle_style = ParagraphStyle(
            "TopicSubtitle",
            parent=styles["Heading2"],
            fontSize=13,
            textColor=colors.HexColor(theme["subtitle"]),
            spaceAfter=16,
            alignment=1,
        )
        section_title_style = ParagraphStyle(
            "SectionTitle",
            parent=styles["Heading2"],
            fontSize=14,
            textColor=colors.HexColor(theme["section_header_text"]),
            spaceAfter=8,
            spaceBefore=4,
            fontName="Helvetica-Bold",
        )
        body_style = ParagraphStyle(
            "TopicBody",
            parent=styles["BodyText"],
            fontSize=11,
            leading=15,
            textColor=colors.HexColor(theme["body"]),
            spaceAfter=10,
        )
        intro_style = ParagraphStyle(
            "IntroBody",
            parent=body_style,
            backColor=colors.HexColor(theme["intro_bg"]),
            borderPadding=8,
        )

        story: list = []
        story.append(Paragraph(topic, title_style))
        story.append(
            Paragraph(
                subtitle or f"Comprehensive Health Report — {topic}",
                subtitle_style,
            )
        )
        story.append(
            Paragraph(
                f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M')}",
                ParagraphStyle(
                    "Date",
                    parent=styles["Normal"],
                    fontSize=9,
                    textColor=colors.HexColor(theme["footer"]),
                    alignment=1,
                ),
            )
        )
        story.append(Spacer(1, 0.15 * inch))
        story.append(
            HRFlowable(
                width="100%", thickness=2, color=colors.HexColor(theme["accent_line"])
            )
        )
        story.append(Spacer(1, 0.2 * inch))

        if intro_text:
            story.append(
                Paragraph("From YouTube Community Manager", section_title_style)
            )
            story.append(Paragraph(intro_text.replace("**", ""), intro_style))
            story.append(Spacer(1, 0.15 * inch))

        section_colors = {
            "Introduction": theme["intro_bg"],
            "Overview": theme["intro_bg"],
            "Causes": theme["causes_bg"],
            "Prevention": theme["prevention_bg"],
            "Treatment & Cure": theme["treatment_bg"],
            "Treatment": theme["treatment_bg"],
            "Design Notes": "#f4f6f7",
        }

        for section_name, section_body in sections.items():
            if not section_body or not section_body.strip():
                continue
            bg = section_colors.get(section_name, "#ffffff")
            header_table = Table(
                [[Paragraph(section_name, section_title_style)]],
                colWidths=[7.2 * inch],
            )
            header_table.setStyle(
                TableStyle(
                    [
                        (
                            "BACKGROUND",
                            (0, 0),
                            (-1, -1),
                            colors.HexColor(theme["section_header_bg"]),
                        ),
                        ("LEFTPADDING", (0, 0), (-1, -1), 10),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                        ("TOPPADDING", (0, 0), (-1, -1), 6),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ]
                )
            )
            story.append(header_table)
            story.append(Spacer(1, 0.08 * inch))

            for paragraph in section_body.split("\n\n"):
                text = paragraph.strip()
                if not text:
                    continue
                para = Paragraph(text.replace("\n", "<br/>"), body_style)
                content_table = Table([[para]], colWidths=[7.2 * inch])
                content_table.setStyle(
                    TableStyle(
                        [
                            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor(bg)),
                            ("LEFTPADDING", (0, 0), (-1, -1), 10),
                            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                            ("TOPPADDING", (0, 0), (-1, -1), 8),
                            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#d5d8dc")),
                        ]
                    )
                )
                story.append(content_table)
            story.append(Spacer(1, 0.15 * inch))

        story.append(
            HRFlowable(
                width="100%", thickness=1, color=colors.HexColor(theme["footer"])
            )
        )
        story.append(Spacer(1, 0.1 * inch))
        story.append(
            Paragraph(
                "Generated by YouTube Community Manager Agent",
                ParagraphStyle(
                    "Footer",
                    parent=styles["Normal"],
                    fontSize=9,
                    textColor=colors.HexColor(theme["footer"]),
                    alignment=1,
                ),
            )
        )

        doc.build(story)
        file_size = os.path.getsize(output_path)
        return f"PDF report successfully generated: {output_path} ({file_size} bytes)"

    except Exception as exc:
        return f"Error generating stylized PDF report: {exc}"


@tool
async def generate_pdf_report(
    title: str,
    content: str,
    output_path: str = "./reports/report.pdf",
    subtitle: str | None = None,
) -> str:
    """Generate a styled PDF report."""
    return await run_in_thread(
        _generate_pdf_report_sync, title, content, output_path, subtitle
    )


def _generate_table_report_sync(
    title: str,
    table_data: list,
    output_path: str = "./reports/table_report.pdf",
) -> str:
    """Generate a PDF report with a data table.

    Args:
        title: The title of the report
        table_data: A list of lists representing table data (first row is header)
        output_path: The path where the PDF will be saved

    Returns:
        A message indicating success or failure with the file path
    """
    try:
        prepare_report_output_path(output_path)

        # Create PDF document
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=0.5 * inch,
            leftMargin=0.5 * inch,
            topMargin=0.5 * inch,
            bottomMargin=0.5 * inch,
        )

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "CustomTitle",
            parent=styles["Heading1"],
            fontSize=20,
            textColor=colors.HexColor("#2c3e50"),
            spaceAfter=20,
            alignment=1,
        )

        # Build content
        story = []
        story.append(Paragraph(title, title_style))
        story.append(Spacer(1, 0.2 * inch))

        # Create table
        if table_data:
            table = Table(table_data)
            table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#3498db")),
                        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                        ("FONTSIZE", (0, 0), (-1, 0), 12),
                        ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
                        ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
                        ("GRID", (0, 0), (-1, -1), 1, colors.black),
                        ("ROWHEIGHTS", (0, 0), (-1, -1), 0.3 * inch),
                    ]
                )
            )
            story.append(table)

        # Build PDF
        doc.build(story)

        file_size = os.path.getsize(output_path)
        return f"Table PDF report successfully generated: {output_path} ({file_size} bytes)"

    except Exception as e:
        return f"Error generating table PDF report: {str(e)}"


@tool
async def generate_table_report(
    title: str,
    table_data: list,
    output_path: str = "./reports/table_report.pdf",
) -> str:
    """Generate a PDF report with a data table."""
    return await run_in_thread(
        _generate_table_report_sync, title, table_data, output_path
    )


YOUTUBE_THEME = {
    "title": "#c4302b",
    "subtitle": "#282828",
    "section_header_bg": "#c4302b",
    "section_header_text": "#ffffff",
    "body": "#282828",
    "accent_line": "#ff0000",
    "footer": "#606060",
    "positive_bg": "#eafaf1",
    "negative_bg": "#fdedec",
    "neutral_bg": "#f4f6f7",
}


def _generate_youtube_report_pdf_sync(
    channel_name: str,
    analysis_date: str,
    stats: dict,
    top_opportunities: list[dict],
    generated_replies: list[dict],
    recommendations: list[str],
    output_path: str = "./reports/youtube_community_report.pdf",
    video_metadata: dict | None = None,
    failed_replies: list[dict] | None = None,
    new_comments: list[dict] | None = None,
) -> str:
    """Generate a YouTube community management PDF report with tables."""
    try:
        prepare_report_output_path(output_path)

        theme = YOUTUBE_THEME
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=0.65 * inch,
            leftMargin=0.65 * inch,
            topMargin=0.65 * inch,
            bottomMargin=0.65 * inch,
        )
        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "YTTitle",
            parent=styles["Heading1"],
            fontSize=22,
            textColor=colors.HexColor(theme["title"]),
            spaceAfter=8,
            alignment=1,
            fontName="Helvetica-Bold",
        )
        section_style = ParagraphStyle(
            "YTSection",
            parent=styles["Heading2"],
            fontSize=13,
            textColor=colors.HexColor(theme["section_header_text"]),
            fontName="Helvetica-Bold",
        )
        body_style = ParagraphStyle(
            "YTBody",
            parent=styles["BodyText"],
            fontSize=10,
            leading=13,
            textColor=colors.HexColor(theme["body"]),
        )

        story: list = []
        story.append(Paragraph("YouTube Community Management Report", title_style))
        story.append(Paragraph(f"Channel: {channel_name}", body_style))
        story.append(Paragraph(f"Analysis Date: {analysis_date}", body_style))
        story.append(Spacer(1, 0.15 * inch))
        story.append(
            HRFlowable(
                width="100%", thickness=2, color=colors.HexColor(theme["accent_line"])
            )
        )
        story.append(Spacer(1, 0.15 * inch))

        video = video_metadata or {}
        if video:
            story.append(Paragraph("Latest Video", section_style))
            story.append(Spacer(1, 0.06 * inch))
            story.append(Paragraph(f"Title: {video.get('title', 'N/A')}", body_style))
            if video.get("url"):
                story.append(Paragraph(f"URL: {video.get('url')}", body_style))
            if video.get("published"):
                story.append(
                    Paragraph(f"Published: {video.get('published')}", body_style)
                )
            if video.get("views"):
                story.append(Paragraph(f"Views: {video.get('views')}", body_style))
            if video.get("video_about"):
                story.append(Spacer(1, 0.08 * inch))
                story.append(Paragraph("What this video is about", section_style))
                story.append(Spacer(1, 0.04 * inch))
                story.append(Paragraph(video["video_about"], body_style))
            description = video.get("description") or video.get("og_description")
            if description:
                story.append(Spacer(1, 0.08 * inch))
                story.append(Paragraph("Video description", section_style))
                story.append(Spacer(1, 0.04 * inch))
                excerpt = description[:1200] + (
                    "..." if len(description) > 1200 else ""
                )
                story.append(Paragraph(excerpt.replace("\n", "<br/>"), body_style))
            story.append(Spacer(1, 0.2 * inch))

        summary_data = [
            ["Metric", "Count"],
            ["Total Comments", str(stats.get("total", 0))],
            ["Positive", str(stats.get("positive", 0))],
            ["Negative", str(stats.get("negative", 0))],
            ["Neutral", str(stats.get("neutral", 0))],
            ["Questions", str(stats.get("questions", 0))],
            ["Suggestions", str(stats.get("suggestions", 0))],
            ["Spam", str(stats.get("spam", 0))],
            ["Unanswered", str(stats.get("unanswered", 0))],
            ["Replies Generated", str(stats.get("replies_generated", 0))],
            ["Replies Posted", str(stats.get("replies_posted", 0))],
            ["Replies Failed", str(stats.get("replies_failed", 0))],
            ["New Comments Generated", str(stats.get("new_comments_generated", 0))],
            ["New Comments Posted", str(stats.get("new_comments_posted", 0))],
        ]
        summary_table = Table(summary_data, colWidths=[3.5 * inch, 2.5 * inch])
        summary_table.setStyle(
            TableStyle(
                [
                    (
                        "BACKGROUND",
                        (0, 0),
                        (-1, 0),
                        colors.HexColor(theme["section_header_bg"]),
                    ),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    (
                        "ROWBACKGROUNDS",
                        (0, 1),
                        (-1, -1),
                        [colors.white, colors.HexColor("#f9f9f9")],
                    ),
                ]
            )
        )
        story.append(Paragraph("Comment Summary", section_style))
        story.append(Spacer(1, 0.08 * inch))
        story.append(summary_table)
        story.append(Spacer(1, 0.2 * inch))

        if top_opportunities:
            opp_data = [["Author", "Category", "Priority", "Comment"]]
            for opp in top_opportunities[:10]:
                opp_data.append(
                    [
                        opp.get("author", "")[:20],
                        opp.get("category", ""),
                        opp.get("engagement_priority", ""),
                        (opp.get("text", "")[:80] + "...")
                        if len(opp.get("text", "")) > 80
                        else opp.get("text", ""),
                    ]
                )
            opp_table = Table(
                opp_data, colWidths=[1.2 * inch, 1 * inch, 0.9 * inch, 3.5 * inch]
            )
            opp_table.setStyle(
                TableStyle(
                    [
                        (
                            "BACKGROUND",
                            (0, 0),
                            (-1, 0),
                            colors.HexColor(theme["section_header_bg"]),
                        ),
                        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                        ("FONTSIZE", (0, 0), (-1, -1), 8),
                        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ]
                )
            )
            story.append(Paragraph("Top Engagement Opportunities", section_style))
            story.append(Spacer(1, 0.08 * inch))
            story.append(opp_table)
            story.append(Spacer(1, 0.2 * inch))

        if generated_replies:
            reply_data = [["Author", "Category", "Reply"]]
            for reply in generated_replies[:15]:
                reply_data.append(
                    [
                        reply.get("author", "")[:20],
                        reply.get("category", ""),
                        (reply.get("reply_text", "")[:100] + "...")
                        if len(reply.get("reply_text", "")) > 100
                        else reply.get("reply_text", ""),
                    ]
                )
            reply_table = Table(
                reply_data, colWidths=[1.2 * inch, 1 * inch, 4.3 * inch]
            )
            reply_table.setStyle(
                TableStyle(
                    [
                        (
                            "BACKGROUND",
                            (0, 0),
                            (-1, 0),
                            colors.HexColor(theme["section_header_bg"]),
                        ),
                        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                        ("FONTSIZE", (0, 0), (-1, -1), 8),
                        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ]
                )
            )
            story.append(Paragraph("Generated Replies", section_style))
            story.append(Spacer(1, 0.08 * inch))
            story.append(reply_table)
            story.append(Spacer(1, 0.2 * inch))

        failed_replies = failed_replies or []
        if failed_replies:
            failed_data = [["Author", "Error", "Comment"]]
            for reply in failed_replies[:10]:
                failed_data.append(
                    [
                        reply.get("author", "")[:20],
                        (reply.get("post_error", "")[:60] + "...")
                        if len(reply.get("post_error", "")) > 60
                        else reply.get("post_error", ""),
                        (reply.get("text", "")[:80] + "...")
                        if len(reply.get("text", "")) > 80
                        else reply.get("text", ""),
                    ]
                )
            failed_table = Table(
                failed_data, colWidths=[1.2 * inch, 2.2 * inch, 3.1 * inch]
            )
            failed_table.setStyle(
                TableStyle(
                    [
                        (
                            "BACKGROUND",
                            (0, 0),
                            (-1, 0),
                            colors.HexColor(theme["section_header_bg"]),
                        ),
                        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                        ("FONTSIZE", (0, 0), (-1, -1), 8),
                        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ]
                )
            )
            story.append(Paragraph("Failed Reply Attempts", section_style))
            story.append(Spacer(1, 0.08 * inch))
            story.append(failed_table)
            story.append(Spacer(1, 0.2 * inch))

        new_comments = new_comments or []
        if new_comments:
            for item in new_comments[:3]:
                story.append(Paragraph("New Video Comment", section_style))
                story.append(Spacer(1, 0.04 * inch))
                story.append(Paragraph(item.get("comment_text", ""), body_style))
                status = "Posted" if item.get("posted") else "Not posted"
                if item.get("post_error"):
                    status = f"Failed: {item.get('post_error')}"
                story.append(Paragraph(f"Status: {status}", body_style))
                story.append(Spacer(1, 0.12 * inch))

        if recommendations:
            story.append(Paragraph("Recommended Creator Actions", section_style))
            story.append(Spacer(1, 0.08 * inch))
            for rec in recommendations:
                story.append(Paragraph(f"• {rec}", body_style))

        story.append(Spacer(1, 0.2 * inch))
        story.append(
            Paragraph(
                "Generated by YouTube Community Manager Agent",
                ParagraphStyle(
                    "Footer",
                    parent=styles["Normal"],
                    fontSize=9,
                    textColor=colors.HexColor(theme["footer"]),
                    alignment=1,
                ),
            )
        )

        doc.build(story)
        file_size = os.path.getsize(output_path)
        return f"YouTube PDF report generated: {output_path} ({file_size} bytes)"
    except Exception as exc:
        return f"Error generating YouTube PDF report: {exc}"


__all__ = [
    "generate_pdf_report",
    "generate_table_report",
    "_generate_stylized_topic_pdf_sync",
    "_generate_pdf_report_sync",
    "_generate_youtube_report_pdf_sync",
]
